### ISSUE TITLE
Mapper时，可以定义一对多外键吗？

### ISSUE THREAD

**Issue by dusdong** [arbing/DapperDal#1]

**Comment by arbing** [comment]
自增主键映射规则是匹配实体类以一个以 Id 命名或结尾的属性。
复杂的映射规则可以继承 ClassMapper<Entity> 自定义。
外键没限制。

**Comment by dusdong** [comment]
能分别给两个实例吗？谢谢~

**Comment by arbing** [comment]
可以先在单元测试里能找找。

你的表字段结果是怎样的

**Comment by dusdong** [comment]
`
public class User
 {
        public long Id { get; set; }
        public string Name { get; set; }
        public List\<Address> Addresses { get; set; }
}

public class Address
{  
      public long Id { get; set; }
      public string Address { get; set; }
      public long UserId { get; set; }
}
`

表 User 的主键 Id 对应到 表 Address 的 外键 UserId，User 与 Address 是 1对多的关系，这个关系该如何定义？
可否通过定义，当 Get User 时，自动取得 对应的 List<Address>？

**Comment by arbing** [comment]
不支持这种场景，只支持单表映射，实体类跟表字段一一对应。

**Comment by dusdong** [comment]
好的，谢谢
